---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - ping:
    - name: Cat a file
      command: cat {{ cat_file_path }}
      register: cat_file
    - debug: msg="{{ cat_file.stdout_lines}}"