---
- hosts: all
  gather_facts: yes
  sudo: yes
  tasks:
    - ping:
    - name: Cat hostname
      command: cat /etc/hostname
      register: hostname
    - debug: msg="{{ hostname.stdout_lines}}"